/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ANGULARDISTRIBUTION
#define ANGULARDISTRIBUTION

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class AngularDistribution : public RooAbsPdf {
public:
  AngularDistribution() {} ; 
  AngularDistribution(const char *name, const char *title,
	      RooAbsReal& _ctheta,
	      RooAbsReal& _phi,
	      RooAbsReal& _g);
  AngularDistribution(const AngularDistribution& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new AngularDistribution(*this,newname); }
  inline virtual ~AngularDistribution() { }

  Double_t evaluate() const override;

protected:

  RooRealProxy ctheta ;
  RooRealProxy phi ;
  RooRealProxy g ;
  
  //Double_t evaluate() const;

private:

  ClassDef(AngularDistribution,1) // Your description goes here...
};
 
#endif
